### PR TITLE
feat(installer): use registry value to determine wsl version

### PR DESCRIPTION
**Pull request by bihe**
approach to solve #25

### CODE REVIEW

**Comment by mriedmann** [comment]
My concern is that this would force ppl to set wsl2 as default whereas DockerInWSL should work fine if wsl2 is only installed. Any ideas on that? @bihe

**Comment by bihe** [comment]
IMHO wsl1 is not officially dead, but I see no real use-cases left which forces one to use wsl1: https://docs.microsoft.com/en-us/windows/wsl/compare-versions. 
Q: on a fresh install (without prior wsl1) isn't v2 the default anyway?

**Comment by mriedmann** [comment]
> on a fresh install (without prior wsl1) isn't v2 the default anyway?

Excellent question, can't answer it. For my installation 20H2 installation it was not. Maybe someone else installed windows recently. 

> MHO wsl1 is not officially dead, but I see no real use-cases left which forces one to use wsl1
There are some network-specific usecases but I agree that this shouldn't be needed. Nevertheless I am a but reluctant to force ppl to use wsl2 as default. 

I will do a quickfix with the current length-check ... leaving this open if it gets a problem again soon. In the long run I hope to be able to use a version-switch or a version-regkey for that.

**Comment by bihe** [comment]
One last idea: The major difference between wsl1 and wsl2 is that the later uses a real kernel. The location of the kernel is in ```%WINDIR%\system32\lxss\tools\```

image


Probably this path is not available for wsl1. So you could "assume" that this is a wsl2 installation

**Comment by mriedmann** [comment]
that is actually a really good idea. Hotfix is on the way. I am also currently setting-up a win11 test-vm (besides a 20H2 and 21H2). Will try to check if we can use the kernel file (or another file inside lxss) to identify wsl reliably. Thx for your support.

**Comment by mriedmann** [comment]
Something I just realized: We could check on the kernel-file to make sure WSL2 is installed and also on the "--import" string in the help text. Without it wsl is not initialized properly (no --install) and the installer cannot run. This might be the best way to do it. 

Any objections? @bihe

**Pull request merged**
